# Generated by Django 3.2.7 on 2021-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('autor', models.CharField(max_length=70)),
                ('isbn', models.IntegerField(blank=True)),
                ('ano_publicacao', models.IntegerField(blank=True)),
                ('genero', models.CharField(max_length=255)),
                ('idioma', models.CharField(blank=True, default='Unknown', max_length=10)),
                ('idioma_original', models.CharField(blank=True, default='Unknown', max_length=10)),
                ('data_cadastro', models.IntegerField(blank=True, default='Unknown')),
            ],
        ),
    ]
