# Generated by Django 3.2.7 on 2021-09-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro_Model',
            new_name='BibliotecaModel',
        ),
    ]
