# Generated by Django 3.2.7 on 2021-09-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_bibliotecamodel_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecamodel',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
